### ISSUE TITLE
Make install error on pop-os

### ISSUE THREAD

**Issue by slottwo** [varlesh/oreo-cursors#13]
What should the program be copying to /usr/share/icons?
Error:
![Captura de tela de 2020-09-10 10-49-27](https://user-images.githubusercontent.com/41028091/92740570-38903a00-f354-11ea-996e-05dadb55180b.png)
System informations:
![Captura de tela de 2020-09-10 10-49-40](https://user-images.githubusercontent.com/41028091/92740610-404fde80-f354-11ea-885d-dc375382de44.png)

**Comment by yochananmarqos** [comment]
I had this issue as well. It appears the `build.sh` isn't actually building anything, therefore the `Makefile` has nothing to copy.

**Comment by SmartFinn** [comment]
Now it requires run generator first. Start from these steps https://github.com/varlesh/oreo-cursors#generate-user-defined-colours
