### ISSUE TITLE
Adding AUR support

### ISSUE THREAD

**Issue by Souravgoswami** [varlesh/oreo-cursors#15]
Hi, I have been giving the cursor to a lot of people. But I have to get each and one from gnome-look or `git clone` the repo. That's not a major problem for me, but what if we provide AUR support for Arch linux users and a deb package for debian users? I can create both! We just need to copy the licence and the cursors to appropriate places, and that's it. Tell me if you are interested!

I also have a Ruby script on cowspeak, which builds debian package with proper permissions automatically (well when you run the script). We can put that in CI and generate cursors automatically? ... Just a thought...

**Comment by yochananmarqos** [comment]
You did [search the AUR](https://aur.archlinux.org/packages/?O=0&SeB=nd&K=oreo+cursors&outdated=&SB=n&SO=a&PP=50&do_Search=Go), right? 😉️
