### ISSUE TITLE
Cursor breakage with Inkscape

### ISSUE THREAD

**Issue by stpnwf** [varlesh/oreo-cursors#18]
Hey, I have been using, and loving the Oreo cursors for a bit now, and I have stumbled upon these issues with Inkscape:
Unsure if the same as issue #1. 
Installed Teal variant from Pling

Had this issue with Inkscape 1.0:

![Peek 2021-05-26 12-09](https://user-images.githubusercontent.com/81482539/119696497-c8bcd380-be3e-11eb-9b64-a3374965531e.gif)

Where this (one instance of) white cursor would show up instead of the Oreo cursor when I had something selected.

But now that I have updated Inkscape to 1.1, I have this issue:

![Peek 2021-05-26 12-16](https://user-images.githubusercontent.com/81482539/119697245-847e0300-be3f-11eb-9ae4-c0aa4a4e6727.gif)

Where the Oreo cursor is replaced (on canvas) by Awaita cursor after I double click on a shape. And it stays until I restart Inkscape.

**Comment by Souravgoswami** [comment]
Hi, does with problem appear with any other cursor theme download from pling?
Also, what is the desktop environment you are running?

**Comment by stpnwf** [comment]
Happened with both Volantes and GoogleDot
I am running Zorin OS 15.3
Gnome Sehll: 3.30.2

**Comment by varlesh** [comment]
it's inkscape built-in cursors (installed on `/usr/share/inkscape/icons/hicolor/cursors/ `):
https://gitlab.com/search?group_id=470642&project_id=3472737&repository_ref=master&scope=blobs&search=cursor_filename&snippets=false

**Comment by stpnwf** [comment]
the built in cursor is that of the first gif, or does that apply to both?
Because, ever since version 1.1. I dont get the cursor from the first gif anymore, just (what I assume to be) Adwaita ones.

**Comment by varlesh** [comment]
If you mean DMZ-Cursor, this cursors last  updated in 2018:
https://salsa.debian.org/gnome-team/dmz-cursor-theme/-/commits/debian/master
I check symlinks later

**Comment by varlesh** [comment]
I'm check DMZ cursors. Yes, Oreo not have some symlinks and rare cursors:
```
14fef782d02440884392942c11205230 sb_h_double_arrow
2870a09082c103050810ffdffffe0204 sb_v_double_arrow
028006030e0e7ebffc7f7070c0600140 h_double_arrow
c7088f0f3e6c8088236ef8e1e3e70000 bd_double_arrow
fcf1c3c7cd4491d801f1e1c78f100000 fd_double_arrow
cross_reverse cross
diamond_cross cross
dot_box_mask dotbox
double_arrow sb_v_double_arrow
draft_large right_ptr
draft_small right_ptr
draped_box dotbox
target dotbox
```
![image](https://user-images.githubusercontent.com/8083855/119934044-3cbdbf80-bf96-11eb-953f-d6330bce5d91.png)

But anyway DMZ not have symlinks or icons to inkscape builtin cursors.
On your gif it's `select-mouseover`:
![image](https://user-images.githubusercontent.com/8083855/119934382-beade880-bf96-11eb-8572-65de95918269.png)
```
if (w->get_window()) {
        // Window may not be open when tool is setup for the first time!
        _cursor_mouseover = load_svg_cursor(w->get_display(), w->get_window(), "select-mouseover.svg");
        _cursor_dragging  = load_svg_cursor(w->get_display(), w->get_window(), "select-dragging.svg");
        // Need to reload select.svg.

```

**Comment by varlesh** [comment]
DMZ (or as you say Adwaita) not have this cursor:
![image](https://user-images.githubusercontent.com/8083855/119934717-498ee300-bf97-11eb-9cf3-f101bff44e37.png)
It's builtin Inkscape cursors

**Comment by varlesh** [comment]
builtin Inkscape cursors very similar with DMZ style... and i think you confusing them ))
Anyway i can't doing anything - it's hardcoded cursors
