### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by CodeWithEnd** [varlesh/oreo-cursors#19]
at the last step when im trying to run "sudo make install"  it shows an error

`
mkdir -p /usr/share/icons
cp -R  /usr/share/icons
cp: missing destination file operand after '/usr/share/icons'
Try 'cp --help' for more information.
make: *** [Makefile:14: install] Error 1`

**Comment by varlesh** [comment]
first, you need generate colors from database:
`ruby generator/convert.rb`
readme updated

**Comment by varlesh** [comment]
duplicate #13

**Comment by nhth31** [comment]
> first, you need generate colors from database: `ruby generator/convert.rb` readme updated

still not work... 
![image](https://github.com/varlesh/oreo-cursors/assets/92625428/833cb2c7-150e-4857-ad41-85d28dfc3f93)
